variables:
  S3_BUCKET_NAME: "howell-info.us"
deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/projects/spotify-library2playlist --recursive --exclude ".gitignore" --exclude "*.yml"
